### ISSUE TITLE
Support smimesign program for signing git commits using S/MIME

### ISSUE THREAD

**Issue by JBlaufussTR** [eclipse-egit/egit#59]
### Description

Support [smimesign](https://github.com/github/smimesign) program for signing commits using S/MIME. The smimesign tool was [developed by GitHub itself](https://github.blog/changelog/2018-09-10-smime-signature-verification/) to support S/MIME commit signing, and works with command-line git with something like this .gitconfig:

```
[user]
	name = My Name
	email = my.name@employer.com
	signingkey = 00000000000000000000000000000000000dummy
[commit]
	gpgsign = true
[gpg]
	format = x509
[gpg "x509"]
	program = smimesign
```

### Motivation

My workplace is in the process of implementing mandatory git commit signing using corporate-issued S/MIME certificates. They have automatically rolled this out to workstations by automatically updating our `.gitconfig` files to use the [smimesign](https://github.com/github/smimesign) program. Even the latest Eclipse 2024-09 (4.33.0) using EGit 7.0.0.202409031743-r org.eclipse.egit gets errors with this configuration when making a commit (which works with command-line git). Here is the error popup:

```
Missing Signing Key

Unable to find a GPG key for signing with key ID `00000000000000000000000000000000000dummy`. Configure the GPG key with committer email address, set git config user.signingKey, or disable commit signing.
```

The configuration works without issue with command-line git on my machine. Only Eclipse has issues with it.

### Alternatives considered

* Leave Eclipse and use command-line git for any operation that makes a commit.
* Use IntelliJ, [which leverages command-line git](https://www.jetbrains.com/help/idea/settings-version-control-git.html) instead of its own implementaiton

**Comment by tomaswolf** [comment]
EGit supports S/MIME (X.509) signatures using an external GPG [since 7.0](https://github.com/eclipse-egit/egit/wiki/New-and-Noteworthy-7.0#x509-signatures). This was tested with `gpgsm`.

I suppose the problem is that EGit first calls `<program> --list-secret-keys --with-colons --batch --no-tty <key_spec>` to figure out whether there is a key at all, and if so, whether it is a signing key, and `smimesign` doesn't understand that.

`smimesign` has the simpler `--list-keys` option to list available signing keys. Apparently the assumption with `smimesign` is that any key returned by `--list-keys` is a signing key. Unfortunately, the command line is different. It also produces output for a human (not easily machine-readable).

EGit also includes the `--batch --no-tty` options in the call for actually signing to ensure that the program does not prompt for passphrases in a terminal (that would never get to the user when invoked from Eclipse). EGit also includes `--output -` to force output of the signature to `stdout`, which might be redundant.

So there seem to be three things to do:
* Check whether `--batch --no-tty` is really necessary with `gpg`/`gpgsm`. If it is, use it only for `gpg`/`gpgsm`.
* Check whether `--output -` is really necessary (probably not).
* Figure out a better way to list keys to determine whether there is a signing key. (In GPG, not all keys are signing keys).

There is of course a third alternative: get `smimesign` updated to understand `--list-secret-keys --with-colons --batch --no-tty` and to understand `-bsau <keySpec> --batch --no-tty --status-fd 2 --output -`. :-)

**Comment by tomaswolf** [comment]
`smimesign --verify` also doesn't seem to be fully gpgsm-compatible in the status lines it produces. gpgsm gives me a VALIDSIG line; I don't see that being generated in the `smimesign` code. VALIDSIG is kind of important because it would report the signature creation time.

So there we have another thing to check: how to deal with a missing signature creation time in validation. Just fill in the git commit/tag timestamp?

**Comment by JBlaufussTR** [comment]
@tomaswolf Thank you for looking into this. I just created an issue in their repo as well, in case they have the ability to add support for the command line options you said are missing, though EGit looks a lot more active.

**Comment by eric-milles** [comment]
@tomaswolf Is there any chance of adding an "External S/MIME Sign" option to this drop-down?  `smimesign` is a nice compact download; GPG is quite a large suite of tools.  Our organization (TR aka Thomson Reuters) has hundreds of java developers and eclipse has been our primary IDE for many years.  This latest requirement for X.509 signed commits means we cannot make use of EGit integration for commits.

![image](https://github.com/user-attachments/assets/ea98f5cc-bdc3-435a-a2ea-354f7181fe53)

Otherwise, is there a possibility of probing the External GPG program to determine if it is `smimesign` and passing different options?

The release notes for 7.0 mention `SignerFactory` SPI.  Is this the intended extension point for adding `smimesign` support?

**Comment by tomaswolf** [comment]
"External GPG" uses the configured `gpg.program`.

Supporting `smimesign`, which would be configured explicitly as gpg.x509.program, which the "External GPG" setting will use, boils down to the two things I mentioned above:

* Check whether `--batch --no-tty` is really necessary with gpg/gpgsm. If it is, use it only for gpg/gpgsm.
* Check whether `--output -` is really necessary (probably not).

The third point (listing keys) is a non-issue for x509 signing. The user has configured at least `gpg.format = x509` (and, for `smimesign`, also `gpg.x509.program = smimesign`), so it's the user's responsibility that a key for signing is available.

Plus on signature verification, `smimesign` does not faithfully produce all the status lines gpgsm does, so we need to have some way to use the commit datetime if there is no signature datetime reported.

**Comment by tomaswolf** [comment]
@eric-milles : I don't quite understand "This latest requirement for X.509 signed commits"... which requirement? Openpgp signatures are still possible, and EGit can now also do SSH signatures. EGit does not require x509 signatures. If you have been using EGit previously, there is nothing new in that area.

That said, I've pushed [Gerrit change 1206209](https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1206209). It makes EGit use only the same command-line options as C git. With that, smimesign should then just work, if configured in the git config.

I hope that a large organization such as yours can thoroughly test this on different platforms (Mac OS, Windows, Linux) with both smimesign and gpgsm. (We have no automated integration tests with gpg/smimesign, and I don't have smimesign in my development environment, so I cannot test manually.)

Install EGit from the [temporary update site](https://ci.eclipse.org/egit/job/egit.gerrit/3199/artifact/org.eclipse.egit.repository/target/repository/) in Eclipse; then test smimesign and gpgsm, also with passphrase-protected keys. Please report here any problems (or also that it works).

**Comment by JBlaufussTR** [comment]
> I don't quite understand "This latest requirement for X.509 signed commits"... which requirement? Openpgp signatures are still possible, and EGit can now also do SSH signatures. EGit does not require x509 signatures. If you have been using EGit previously, there is nothing new in that area.

To clarify, I think he's referring to the requirements of internal corporate policies.

> Install EGit from the [temporary update site](https://ci.eclipse.org/egit/job/egit.gerrit/3199/artifact/org.eclipse.egit.repository/target/repository/) in Eclipse; then test smimesign and gpgsm, also with passphrase-protected keys. Please report here any problems (or also that it works).

I gave it a try, and it works if I select `External GPG` and if I override the program in the `.gitconfig` with the full path:
![image](https://github.com/user-attachments/assets/fdbbaca7-a418-4831-9e07-dbb2a34accb6).

I'm still getting the same error as in my original report when I have `Bouncy Castle Library` selected (but I suppose that's expected, I was not aware of that setting until @eric-milles mentioned it).

When using `External GPG` and the `.gitconfig` from my original report (without the full path), I am getting the following error, even though `smimesign` is located on my `$PATH` at `/usr/local/bin`, and even when I set the `GPG Executable` like this:

![image](https://github.com/user-attachments/assets/7803a134-0e8e-4992-b454-ee0e5de1a0e6)

![image](https://github.com/user-attachments/assets/7c53d64d-3835-4b17-8520-282e491feba1)

```
org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of commit command
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:304)
	at org.eclipse.egit.core.op.CommitOperation.commit(CommitOperation.java:256)
	at org.eclipse.egit.core.op.CommitOperation$1.run(CommitOperation.java:208)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2451)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2476)
	at org.eclipse.egit.core.op.CommitOperation.execute(CommitOperation.java:217)
	at org.eclipse.egit.ui.internal.commit.CommitJob.run(CommitJob.java:135)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: External program failed (Cannot run program "smimesign": error=2, No such file or directory): smimesign -bsau 734f2145d8e16d6e427019e2cd077ef232f49426 --status-fd 2
	at org.eclipse.egit.core.internal.signing.ExternalProcessRunner.run(ExternalProcessRunner.java:105)
	at org.eclipse.egit.core.internal.signing.ExternalGpgSigner.sign(ExternalGpgSigner.java:205)
	at org.eclipse.jgit.lib.Signer.signObject(Signer.java:73)
	at org.eclipse.jgit.api.CommitCommand.sign(CommitCommand.java:335)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:281)
	... 7 more
Caused by: java.io.IOException: Cannot run program "smimesign": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1170)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1089)
	at org.eclipse.jgit.util.FS.runProcess(FS.java:2126)
	at org.eclipse.jgit.util.FS.execute(FS.java:2259)
	at org.eclipse.egit.core.internal.signing.ExternalProcessRunner.run(ExternalProcessRunner.java:56)
	... 11 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:295)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:225)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1126)
	... 15 more
```

I'm on Mac OS X, and it looks like I might have some $PATH issues to debug to get this working a bit more smoothly (the Eclipse Terminal also starts up with a different path than my typical terminal shell, until I add `--login` like described [here](https://superuser.com/a/1231288)).

I'll work on testing this a little more after the holidays.

Thank you for your help!

**Comment by tomaswolf** [comment]
You probably have defined
```
gpg.x509.program = smimesign
```
Try
```
gpg.x509.program = /usr/local/bin/smimesign
```
EGit uses the program as specified in the git config. The executable defined in the UI is taken only as fallback if no program is defined in the git config.

I could try improving this a bit. One idea might be to call the program not directly but via the shell (with --login).

**Comment by tomaswolf** [comment]
Or wait -- you wrote you already had the full path in the git config. Hmmm. Then I don't see why the exception message says `Cannot run program "smimesign"`. It must have picked up plain "smimesign" (without the path) somewhere.

**Comment by tomaswolf** [comment]
I've pushed [a follow-up commit](https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1206216) that explicitly looks up the program on $PATH.

Use the [new temporary update site](https://ci.eclipse.org/egit/job/egit.gerrit/3200/artifact/org.eclipse.egit.repository/target/repository/) for testing, please.

**Comment by eric-milles** [comment]
I was able to set the External GPG Executable to an adapter batch script:
```bat
@ECHO OFF
java %USERPROFILE%\SigningAdapter.java %*
REM -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y
```

```java
import java.io.*;
import java.util.*;

public class SigningAdapter {
  public static void main(String[] args) {
    if (Arrays.asList(args).contains("--list-secret-keys")) {
      System.out.println("crs:a:b:c:d:e:f:g:h:i:j:ks");
    } else { // -bsau, <ID>, --batch, --no-tty, --status-fd, 2, --output, -
      try { // TODO: put args to list and drop "--batch", etc. with remove
        var b = new ProcessBuilder("smimesign.exe", args[0], args[1], args[4], args[5]);
        var p = b.inheritIO().start();
        System.exit(p.waitFor());
      } catch (Exception e) {
        System.err.println(e.getMessage());
      }
    }
  }
}
```

Given this and no "gpg.x509.program" property, a commit can be signed via `smimesign`.  I had hoped I could name it "smimesign.bat" and co-locate it with "smimesign.exe".  However the windows pathspec says `exe` recognized before `bat`.  In any case, this did work for the happy path case.  Once a commit is signed, is there any way to verify that is the case in the UI?

**Comment by tomaswolf** [comment]
Try the update site; you should not need this wrapper. It should just work out of the box with the following two git configs:
```
[gpg]
    format = x509
[gpg "x509"]
    program = /path/to/smimesign # Or just smimesign if it's on $PATH
```
(Plus the user.signingKey, if needed.)

**Comment by tomaswolf** [comment]
On Windows, it would be
```
[gpg "x509"]
   program = C:/path/to/smimesign.exe # Or just smimesign.exe if it's on %PATH%
```

**Comment by tomaswolf** [comment]
> Once a commit is signed, is there any way to verify that is the case in the UI?

Yes, in the history view. The lower left pane shows the commit, which includes the signature info if the preference at Preferences->Version Control->Git->History ("Verify Signatures") is switched on.

**Comment by tomaswolf** [comment]
The original temporary update site had vanished. Please use the [new update site](https://ci.eclipse.org/egit/job/egit.gerrit/3215/artifact/org.eclipse.egit.repository/target/repository/).

**Comment by JBlaufussTR** [comment]
> Or wait -- you wrote you already had the full path in the git config. Hmmm. Then I don't see why the exception message says `Cannot run program "smimesign"`. It must have picked up plain "smimesign" (without the path) somewhere.

Sorry if I was confusing. I got the error when I only had:

```
[gpg "x509"]
	program = smimesign
```

When I changed it to:

```
[gpg "x509"]
	program = /usr/local/bin/smimesign
```

...it worked.

I suspect the issue probably isn't with your code so much as how `$PATH` is getting set on Mac OS.  It appears Eclipse is not getting (by default) the same `$PATH` that I get the Mac OS terminal application.  I saw similar behavior when trying it with the Eclipse Terminal view, which I was able to work around _for the Terminal view_ by adding the `--login` argument to its configuration as described [here](https://superuser.com/questions/28344/path-env-variable-on-mac-os-x-and-or-eclipse/1231288#1231288).

> I could try improving this a bit. One idea might be to call the program not directly but via the shell (with --login).

I think doing something like using the shell with `--login` might make things more user friendly, if it eliminates and discrepancy between the `$PATH` Eclipse sees and the `$PATH` the user is used to having in their terminal.

I'll give your new update a try sometime this week.

**Comment by msohn** [comment]
On Mac if you start Eclipse e.g. from the dock or from spotlight you may need to ensure that the environment variable PATH is set, e.g. by using a launch agent, see https://discussions.apple.com/thread/253877043

**Comment by tomaswolf** [comment]
@JBlaufussTR , @eric-milles : any news here? The [update site](https://ci.eclipse.org/egit/job/egit.gerrit/3215/artifact/org.eclipse.egit.repository/target/repository/) is still there.

I'm looking for confirmation that this works on all three platforms (Windows, Linux, MacOS), using either gpgsm or smimesign. (With the preferences in Eclipse set to "External GPG", no program path specified; simply using the git config.)

The next EGit release is scheduled for mid-March, and we'll finalize the release around end of February already. So now's the time to test and report your findings if you want this in the next EGit release.

**Comment by eric-milles** [comment]
@tomaswolf Using Eclipse 4.33 with egit 7.2.0 from the update site you provided, a signed commit fails at the first stage where `user.signingKey` is validated.

![Image](https://github.com/user-attachments/assets/34e986a4-9b2c-4430-b4d3-27bd677c5f35)

**Comment by JBlaufussTR** [comment]
@eric-milles Did you set [Eclipse Settings] > `Version Control (Team)` > `Git` > `Committing` > `For singing commits and tags use:` to `External GPG`?

![Image](https://github.com/user-attachments/assets/241b0e6e-1fb2-4a91-bce4-d522f1393d27)

I still get the error you got if it's set to the default `Bouncy Castle Library`.

> On Mac if you start Eclipse e.g. from the dock or from spotlight you may need to ensure that the environment variable PATH is set, e.g. by [configuring it in /etc/launchd.conf](https://www.bounga.org/tips/2020/04/07/instructs-mac-os-gui-apps-about-path-environment-variable/)

It works for me now with the newer update site that @tomaswolf uploaded without me making any Mac OS path changes. It looks like I already had `/usr/local/bin` in the `/etc/paths` file that site talks about for later MacOS versions, but I don't see that when I `echo $PATH` from the Eclipse Terminal.  Don't know if `/etc/paths` was updated on my machine recently without my knowledge or something @tomaswolf did made it pick up a more complete $PATH. In any case, it's working with git commit signing.

> any news here? The [update site](https://ci.eclipse.org/egit/job/egit.gerrit/3215/artifact/org.eclipse.egit.repository/target/repository/) is still there.

@tomaswolf I can test MacOS with smimesign. I gave it a try with a fresh eclipse-jee-2024-09-R-macosx-cocoa-aarch64 install, fresh workspace, and the most recent update site. I am able to commit with signed commits without having to do anything to the path to the executable. E.g. this works for me:

```
[gpg "x509"]
	program = smimesign
```

The commits verify when using `git verify-commit` on the command line:

```
git verify-commit 7ec21f333c88d9c4faaf34da5af6e1fe91ae7255
smimesign: Signature made using certificate ID 0x00000000000000000000000000000000000dummy
smimesign: Good signature from "CN=my.name@employer.com,O=Employer Inc,2.5.4.97=#13104e545255532b44452d32383134333938"
```
I enabled commit verification in Eclipse like you described in your earlier comments, but that's not working:

![Image](https://github.com/user-attachments/assets/d7eb72cd-708d-4624-a818-ec84b1d6f1c1)

Here's the full info from the `Error Log`:

```
eclipse.buildId=4.33.0.20240905-0613
java.version=21.0.4
java.vendor=Eclipse Adoptium
BootLoader constants: OS=macosx, ARCH=aarch64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/jeffb/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch aarch64 -product org.eclipse.epp.package.jee.product -keyring /Users/jeffb/.eclipse_keyring

org.eclipse.core.jobs
Error
Thu Jan 23 16:24:21 CST 2025
An internal error occurred during: "Building Commit Info".

java.lang.NullPointerException: Cannot invoke "java.time.Instant.toEpochMilli()" because "instant" is null
	at java.base/java.util.Date.from(Date.java:1361)
	at org.eclipse.egit.core.internal.signing.ExternalGpgSignatureVerifier.fromGpg(ExternalGpgSignatureVerifier.java:285)
	at org.eclipse.egit.core.internal.signing.ExternalGpgSignatureVerifier.lambda$0(ExternalGpgSignatureVerifier.java:117)
	at org.eclipse.egit.core.internal.signing.ExternalProcessRunner.run(ExternalProcessRunner.java:78)
	at org.eclipse.egit.core.internal.signing.ExternalGpgSignatureVerifier.verify(ExternalGpgSignatureVerifier.java:116)
	at org.eclipse.jgit.lib.SignatureVerifiers.verify(SignatureVerifiers.java:216)
	at org.eclipse.jgit.lib.SignatureVerifiers.verify(SignatureVerifiers.java:168)
	at org.eclipse.egit.ui.internal.history.CommitInfoBuilder.format(CommitInfoBuilder.java:128)
	at org.eclipse.egit.ui.internal.history.FormatJob.run(FormatJob.java:69)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by tomaswolf** [comment]
> I enabled commit verification in Eclipse like you described in your earlier comments, but that's not working:
> 
> ```
> java.lang.NullPointerException: Cannot invoke "java.time.Instant.toEpochMilli()" because "instant" is null
> ```

Thanks; that's definitely a bug. Smimesign doesn't give the timestamp the signature was created. I'll fix that tonight and will publish a new update site.

**Comment by eric-milles** [comment]
This is the bit that I missed:

> preferences in Eclipse set to "External GPG", no program path specified

Is that setting required to enable this whole path?  Or should providing this be enough:

```
[gpg]
    format = x509
[gpg "x509"]
   program = smimesign
[user]
   email = ...
   name = ...
   signingKey = ...
```

**Comment by tomaswolf** [comment]
The git config should be enough. You do not need to set the path to the smimesign/gpg executable in Eclipse/EGit. That's intended just as an override of gpg.x509.program or gpg.program in case the setting in the git config doesn't work from Eclipse, or someone on purpose wants to run different tools with command-line git and EGit.

I'll fix the bug reported above tonight (in about 4 hours in my time zone) and publish here a link to a new update site then.

**Comment by tomaswolf** [comment]
New [update site](https://ci.eclipse.org/egit/job/egit.gerrit/3229/artifact/org.eclipse.egit.repository/target/repository/) with the signature verification fixed is available.

**Comment by tomaswolf** [comment]
> New [update site](https://ci.eclipse.org/egit/job/egit.gerrit/3229/artifact/org.eclipse.egit.repository/target/repository/) with the signature verification fixed is available.

@JBlaufussTR @eric-milles : could you re-test, please?

**Comment by tomaswolf** [comment]
Ping??

**Comment by eric-milles** [comment]
I was able to commit and verify in history on Windows, given External GPG selected and edit box empty and `git.x509.program=smimesign`

**Comment by JBlaufussTR** [comment]
> > New [update site](https://ci.eclipse.org/egit/job/egit.gerrit/3229/artifact/org.eclipse.egit.repository/target/repository/) with the signature verification fixed is available.
> 
> [@JBlaufussTR](https://github.com/JBlaufussTR) [@eric-milles](https://github.com/eric-milles) : could you re-test, please?

I tested again on Mac OS with a fresh eclipse-jee-2024-09-R-macosx-cocoa-aarch64 and that update site.  I enabled external gpg and signature verification, but made no other config changes from the defaults.  I was able to make a test commit successfully, and when viewing the commits it had a `gpgsm: Good signature from "CN=...`.  I got no error popups.  The commits signature also verified with `git verify-commit ...` on the command line.

**Comment by msohn** [comment]
Nice, I could x509 sign commits and tags on MacOS. 

Though it seems to be impossible to set a tag message, the tag message field doesn't accept any input.
I guess that's an independent issue.

I could verify commit signatures.
Is there a way to verify a tag signature ?

**Comment by tomaswolf** [comment]
> Nice, I could x509 sign commits and tags on MacOS.

Using gpgsm? Or smimesign?

> Is there a way to verify a tag signature ?

We have not implemented anything in EGit to actually verify and show tag signatures. It could perhaps be done in `TagPropertySource` showing the signature in the properties view for a tag.

If I see this correctly, we now have the following positive tests:

| | Windows | MacOS | Linux |
|----|----|----|----|
| gpgsm| ? | Jeff<br/>Thomas<br/>Matthias? | |
| smimesign | Eric | ? | |

Is that correct? Could I get confirmation
* that it works on Windows if gpgsm is used<br/>(from the Gpg4Win distro; don't know if it would work from EGit with the mingw-based gpg that git-for-windows distributes and in a normal git-for-windows installation that mingw-gpg isn't even on the Windows %PATH%), and
* that it works with smimesign on MacOS?

I guess if it works on MacOS it'll also work on Linux, though explicit confirmations for Linux would be nice.

The main purpose of testing with gpg/gpgsm is to ensure that it still prompts for passphrases in a dialog after I've removed the explicit `--batch --no-tty` arguments.

Note: when viewing the commits and smimesign is used to verify the signature, EGit should show "smimesign: Good signature from...". When gpgsm is used, it should say "gpgsm: Good signature from...". The prefix is read from the called program's stderr. If you see "gpgsm: ..." and you're sure you used smimesign, then there is something still not entirely right. (Or your smimesign prefixes its lines by "gpgsm: ".)

**Comment by msohn** [comment]
I tested using smimesign with the following configuration in `~/.gitconfig`:

```
[gpg]
    format = x509
[gpg "x509"]
    program = smimesign
```

Finding smimesign only worked when starting Eclipse from a shell. I guess when it's started from the dock it's not looking at my `~/.bash_profile`. Configuring the path in Eclipse settings works around this.

**Comment by tomaswolf** [comment]
> I tested using smimesign

OK, I've updated the table above.

> Finding smimesign only worked when starting Eclipse from a shell.

Strange. On MacOS, we actually execute `bash --login -c 'which smimesign'` to find the program. See the code at https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1206216/8/org.eclipse.egit.core/src/org/eclipse/egit/core/internal/signing/ExternalGpg.java#82 . Perhaps stepping through that you could see why this wouldn't work on your machine. Is `SystemReader.isMacOS() == true`?

**Comment by msohn** [comment]
Also tried gpgsm using the same cert I used for smimesign but that fails with

`External program failed (1: gpgsm: can't sign using '116367d7ffb40ebaabaae0a2e77d946d8d36cffc': No secret key`

I tried debugging EGit but couldn't, starting the IDE in the debugger fails, looks like the target platform egit-4.34 (I currently use 2024-12) needs an update.

**Comment by tomaswolf** [comment]
> No secret key

That looks like a problem with importing that certificate. GPG doesn't know the private key that would go with it.

**Comment by tomaswolf** [comment]
I'm going to rebase and then submit the two Gerrit changes for this.

Regarding $PATH on Mac:

* `bash --login -c 'which PROGRAM_NAME'` has been the old way of doing this, and is also used in JGit [here](https://github.com/eclipse-jgit/jgit/blob/523878915ccf6f013d084c552d6b7219d0dfc02a/org.eclipse.jgit/src/org/eclipse/jgit/util/FS_POSIX.java#L142). It works on my old Mac and it picks up the $PATH as set in my .bash_profile.
* `sh -l -c`, which is used in FS_POSIX.runInShell(), does _not_ pick up the $PATH as set via .profile on my Mac. (I have ~/.profile symlinked to ~/.bash_profile). This appears to be a bug in sh on the Mac: it just doesn't execute .profile.
* Starting with OS X 10.15, Apple switched the default shell from bash to zsh, and bash since then may print a warning on stderr about this. Is it possible that this interferes with our calling bash to find the program? We expect a single line containing the full path to the executable.

A simple test that can be done in any Mac terminal is to run
```
$ PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin" bash --login -c 'echo $PATH'
# Should write the path as set in .bash_profile
$ PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin" sh -l -c 'echo $PATH'
# Writes the short path as defined on the command line on my Mac
```

**Comment by msohn** [comment]
I use MacOS 15.3 and my login shell is bash:
```
$ echo $SHELL
/bin/bash
```
I symlinked `~/.bash_profile` from `~/.profile`.

For me both these tests print the full path as defined in my `~/.bash_profile`.

**Comment by tomaswolf** [comment]
> For me both these tests print the full path as defined in my `~/.bash_profile`.

So I don't understand why it wouldn't find smimesign for you with Eclipse called from the dock.

**Comment by tomaswolf** [comment]
Both changes submitted.
